version: '3.4'

x-env-variables: &env-variables
  DB_HOST: db
  DB_USE_SSL: "False"
  DEBUG: "True"

services:
  django: 
    build: .
    environment: *env-variables
    command: python webpage/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  migration:
    build: .
    environment: *env-variables
    command: python webpage/manage.py migrate
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      - "3306:3306"
    command: ["--init-file", "/docker-entrypoint-initdb.d/init.sql"]
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
