TECHNOLOGIES = [
    'C',
    'C++',
    'SQL',
    'CSS',
    'Bash',
    'HTML',
    'gRPC',
    'React',
    'Linux',
    'Redis',
    'WebRTC',
    'GoLang',
    'Docker',
    'Python',
    'Django',
    'Heroku', 
    'Locust',
    'Celery',
    'FFMPEG',
    'MongoDB',
    'PostgreSQL', 
    'ReactNative',
    'WebSockets (WS)',
    'JavaScript (JS)',
    'Amazon Web Service (AWS)',
    'Http Live Streaming (HLS)',
    'Protocol Buffers (Protobuf)',
    'Google Cloud Platform (GCP)',
    'Django REST Framework (DRF)',
    'Adptative Bitrate Streaming (ABS)',
]
