# Generated by Django 5.0 on 2024-01-02 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article_type', models.CharField(choices=[('fun', 'For Fun'), ('backend', 'Back-End'), ('cs', 'Computer Science'), ('frontend', 'Front-End'), ('midend', 'Mid-End'), ('career', 'Carreira'), ('community', 'Comunidade'), ('sdev', 'Desenvolvimento de Software')], max_length=32)),
                ('technologies', models.ManyToManyField(to='projects.technology')),
            ],
            options={
                'verbose_name': 'artigo',
                'verbose_name_plural': 'artigos',
                'ordering': ('-created_at',),
                'default_related_name': 'articles',
            },
        ),
    ]
