# Generated by Django 5.0 on 2024-01-01 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_commit', models.DateField()),
                ('last_commit', models.DateField()),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('name', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('deploy', models.URLField(blank=True, null=True)),
                ('source_code', models.URLField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('fun', 'For Fun'), ('backend', 'Back-End'), ('cs', 'Computer Science'), ('frontend', 'Front-End'), ('midend', 'Mid-End')])),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tecnologia',
                'verbose_name_plural': 'tecnologias',
            },
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.SmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('alter_text', models.TextField(blank=True, null=True)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'asset do projeto',
                'verbose_name_plural': 'assets dos projetos',
                'default_related_name': 'assets',
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'detalhe do projeto',
                'verbose_name_plural': 'detalhes dos projetos',
                'default_related_name': 'details',
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.SmallIntegerField(blank=True, null=True)),
                ('is_equipe_tech', models.BooleanField(default=False)),
                ('used_by', models.CharField(blank=True, choices=[('front', 'FrontEnd'), ('mobile', 'Mobile'), ('qa', 'QA')], null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.technology')),
            ],
            options={
                'verbose_name': 'tecnologia do projeto',
                'verbose_name_plural': 'tecnologias dos projetos',
                'default_related_name': 'techs',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(through='projects.ProjectTechnology', to='projects.technology'),
        ),
    ]
